"""
Integration tests for DocxParser.

These tests verify that the parser components work together correctly
with real DOCX files generated by python-docx.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List

import pytest

from docx_parser import parse_docx, DocxParser
from docx_parser.models import (
    HierarchyMode,
    HorizontalMergeMode,
    OutputFormat,
    ParseResult,
    TableFormat,
    VerticalMergeMode,
)


# ============================================================================
# Basic Parsing Tests
# ============================================================================


@pytest.mark.integration
class TestBasicParsing:
    """Tests for basic document parsing."""

    def test_parse_simple_docx(self, sample_docx):
        """Test parsing a simple DOCX file."""
        result = parse_docx(sample_docx)

        assert isinstance(result, ParseResult)
        assert result.content
        assert "Test Document" in result.content
        assert "test paragraph" in result.content

    def test_parse_empty_docx(self, empty_docx):
        """Test parsing an empty DOCX file."""
        result = parse_docx(empty_docx)

        assert isinstance(result, ParseResult)
        # Empty document may have minimal content
        assert result.content is not None

    def test_parse_returns_source_path(self, sample_docx):
        """Test that source path is preserved in result."""
        result = parse_docx(sample_docx)

        assert result.source == sample_docx

    def test_parse_with_output_dir(self, sample_docx, output_dir):
        """Test parsing with output directory."""
        result = parse_docx(sample_docx, output_dir=output_dir)

        assert isinstance(result, ParseResult)
        # Images directory should be created
        images_dir = output_dir / "images" / sample_docx.stem
        assert images_dir.exists()


@pytest.mark.integration
class TestOutputFormats:
    """Tests for different output formats."""

    def test_markdown_output(self, sample_docx):
        """Test markdown output format."""
        result = parse_docx(sample_docx, output_format=OutputFormat.MARKDOWN)

        assert result.output_format == OutputFormat.MARKDOWN
        assert result.content == result.markdown_content

    def test_text_output(self, sample_docx):
        """Test plain text output format."""
        result = parse_docx(sample_docx, output_format=OutputFormat.TEXT)

        assert result.output_format == OutputFormat.TEXT
        assert result.content == result.text_content
        # Should not contain markdown formatting
        assert "# " not in result.content or result.content.count("#") == 0

    def test_json_output(self, sample_docx):
        """Test JSON output format."""
        result = parse_docx(sample_docx, output_format=OutputFormat.JSON)

        assert result.output_format == OutputFormat.JSON
        # Content should be a list of blocks
        assert isinstance(result.content, list)
        assert len(result.content) > 0

    def test_json_output_structure(self, sample_docx):
        """Test JSON output block structure."""
        result = parse_docx(sample_docx, output_format=OutputFormat.JSON)

        for block in result.content:
            assert "type" in block
            assert block["type"] in ["paragraph", "heading", "table", "image"]


# ============================================================================
# Metadata Extraction Tests
# ============================================================================


@pytest.mark.integration
class TestMetadataExtraction:
    """Tests for metadata extraction."""

    def test_metadata_extraction_enabled(self, sample_docx):
        """Test metadata extraction when enabled."""
        result = parse_docx(sample_docx, extract_metadata=True)

        assert result.metadata is not None
        assert result.metadata.file_name == sample_docx.name

    def test_metadata_extraction_disabled(self, sample_docx):
        """Test metadata extraction when disabled."""
        result = parse_docx(sample_docx, extract_metadata=False)

        assert result.metadata is None

    def test_metadata_to_langchain(self, sample_docx):
        """Test LangChain-compatible metadata conversion."""
        result = parse_docx(sample_docx, extract_metadata=True)

        lc_metadata = result.to_langchain_metadata()
        assert isinstance(lc_metadata, dict)
        assert "source" in lc_metadata


# ============================================================================
# Heading Detection Tests
# ============================================================================


@pytest.mark.integration
class TestHeadingDetection:
    """Tests for heading hierarchy detection."""

    def test_style_based_heading_detection(self, sample_docx_with_headings):
        """Test style-based heading detection."""
        result = parse_docx(
            sample_docx_with_headings,
            hierarchy_mode=HierarchyMode.STYLE,
        )

        # Should contain markdown headings
        assert "# " in result.content or "## " in result.content

    def test_heading_detection_none_mode(self, sample_docx_with_headings):
        """Test no heading detection."""
        result = parse_docx(
            sample_docx_with_headings,
            hierarchy_mode=HierarchyMode.NONE,
        )

        # Should not add heading markers
        # (Original content may have # from other sources)
        assert result.content

    def test_auto_heading_detection(self, sample_docx_with_headings):
        """Test auto heading detection mode."""
        result = parse_docx(
            sample_docx_with_headings,
            hierarchy_mode=HierarchyMode.AUTO,
        )

        # Should detect headings
        assert result.content

    def test_max_heading_level(self, sample_docx_with_headings):
        """Test max heading level constraint."""
        result = parse_docx(
            sample_docx_with_headings,
            hierarchy_mode=HierarchyMode.STYLE,
            max_heading_level=2,
        )

        # Should not have headings deeper than level 2
        assert "### " not in result.content


# ============================================================================
# Table Parsing Tests
# ============================================================================


@pytest.mark.integration
class TestTableParsing:
    """Tests for table parsing."""

    def test_simple_table_markdown(self, sample_docx_with_tables):
        """Test simple table parsing to markdown."""
        result = parse_docx(
            sample_docx_with_tables,
            table_format=TableFormat.MARKDOWN,
        )

        # Should contain markdown table formatting
        assert "|" in result.content
        assert "---" in result.content

    def test_simple_table_html(self, sample_docx_with_tables):
        """Test simple table parsing to HTML."""
        result = parse_docx(
            sample_docx_with_tables,
            table_format=TableFormat.HTML,
        )

        assert "<table>" in result.content
        assert "<tr>" in result.content
        assert "</table>" in result.content

    def test_simple_table_json(self, sample_docx_with_tables):
        """Test simple table parsing to JSON."""
        result = parse_docx(
            sample_docx_with_tables,
            table_format=TableFormat.JSON,
        )

        # Should be valid JSON
        assert "{" in result.content

    def test_simple_table_text(self, sample_docx_with_tables):
        """Test simple table parsing to text."""
        result = parse_docx(
            sample_docx_with_tables,
            table_format=TableFormat.TEXT,
        )

        # Should contain tab-separated values
        assert "\t" in result.content


# ============================================================================
# Image Extraction Tests
# ============================================================================


@pytest.mark.integration
class TestImageExtraction:
    """Tests for image extraction."""

    def test_extract_images_enabled(self, sample_docx_with_images, output_dir):
        """Test image extraction when enabled."""
        result = parse_docx(
            sample_docx_with_images,
            output_dir=output_dir,
            extract_images=True,
        )

        # Should have images
        assert result.image_count > 0
        assert len(result.images_list) > 0

    def test_extract_images_disabled(self, sample_docx_with_images, output_dir):
        """Test image extraction when disabled."""
        result = parse_docx(
            sample_docx_with_images,
            output_dir=output_dir,
            extract_images=False,
        )

        # Should have image mapping but no extracted data
        assert result.image_count > 0
        assert result.images_list[0].data is None

    def test_image_placeholders_in_content(self, sample_docx_with_images):
        """Test image placeholders appear in content."""
        result = parse_docx(sample_docx_with_images)

        # Should contain image placeholders
        assert "[IMAGE_" in result.content

    def test_custom_image_placeholder(self, sample_docx_with_images):
        """Test custom image placeholder format."""
        parser = DocxParser(image_placeholder="<<IMG_{num}>>")
        result = parser.parse(sample_docx_with_images)

        assert "<<IMG_" in result.content

    def test_image_files_saved(self, sample_docx_with_images, output_dir):
        """Test that image files are saved to disk."""
        result = parse_docx(
            sample_docx_with_images,
            output_dir=output_dir,
            extract_images=True,
        )

        # Check that files exist
        for img_path in result.images.values():
            assert img_path.exists()


# ============================================================================
# Merge Mode Tests
# ============================================================================


@pytest.mark.integration
class TestMergeModes:
    """Tests for cell merge handling modes."""

    def test_vertical_merge_repeat(self, sample_docx_with_tables):
        """Test vertical merge repeat mode."""
        result = parse_docx(
            sample_docx_with_tables,
            vertical_merge=VerticalMergeMode.REPEAT,
        )

        assert result.content

    def test_vertical_merge_empty(self, sample_docx_with_tables):
        """Test vertical merge empty mode."""
        result = parse_docx(
            sample_docx_with_tables,
            vertical_merge=VerticalMergeMode.EMPTY,
        )

        assert result.content

    def test_horizontal_merge_expand(self, sample_docx_with_tables):
        """Test horizontal merge expand mode."""
        result = parse_docx(
            sample_docx_with_tables,
            horizontal_merge=HorizontalMergeMode.EXPAND,
        )

        assert result.content

    def test_horizontal_merge_single(self, sample_docx_with_tables):
        """Test horizontal merge single mode."""
        result = parse_docx(
            sample_docx_with_tables,
            horizontal_merge=HorizontalMergeMode.SINGLE,
        )

        assert result.content


# ============================================================================
# Batch Processing Tests
# ============================================================================


@pytest.mark.integration
class TestBatchProcessing:
    """Tests for batch document processing."""

    def test_parse_multiple_documents(self, sample_docx, empty_docx):
        """Test parsing multiple documents at once."""
        results = parse_docx([sample_docx, empty_docx])

        assert isinstance(results, list)
        assert len(results) == 2
        assert all(isinstance(r, ParseResult) for r in results)

    def test_batch_preserves_order(self, sample_docx, sample_docx_with_tables, empty_docx):
        """Test that batch processing preserves document order."""
        paths = [sample_docx, sample_docx_with_tables, empty_docx]
        results = parse_docx(paths)

        for path, result in zip(paths, results):
            assert result.source == path


# ============================================================================
# Error Handling Tests
# ============================================================================


@pytest.mark.integration
class TestErrorHandling:
    """Tests for error handling."""

    def test_corrupted_docx_raises_error(self, corrupted_docx):
        """Test that corrupted DOCX raises appropriate error."""
        with pytest.raises(Exception):
            parse_docx(corrupted_docx)

    def test_non_existent_file_raises_error(self, tmp_path):
        """Test that non-existent file raises error."""
        with pytest.raises(Exception):
            parse_docx(tmp_path / "nonexistent.docx")


# ============================================================================
# Save File Tests
# ============================================================================


@pytest.mark.integration
class TestSaveFile:
    """Tests for save_file functionality."""

    def test_save_markdown(self, sample_docx, output_dir):
        """Test saving markdown file."""
        result = parse_docx(
            sample_docx,
            output_dir=output_dir,
            output_format=OutputFormat.MARKDOWN,
            save_file=True,
        )

        md_path = output_dir / f"{sample_docx.stem}.md"
        assert md_path.exists()

    def test_save_text(self, sample_docx, output_dir):
        """Test saving text file."""
        result = parse_docx(
            sample_docx,
            output_dir=output_dir,
            output_format=OutputFormat.TEXT,
            save_file=True,
        )

        txt_path = output_dir / f"{sample_docx.stem}.txt"
        assert txt_path.exists()

    def test_save_json(self, sample_docx, output_dir):
        """Test saving JSON file."""
        result = parse_docx(
            sample_docx,
            output_dir=output_dir,
            output_format=OutputFormat.JSON,
            save_file=True,
        )

        json_path = output_dir / f"{sample_docx.stem}.json"
        assert json_path.exists()


# ============================================================================
# DocxParser Class Tests
# ============================================================================


@pytest.mark.integration
class TestDocxParserClass:
    """Tests for DocxParser class directly."""

    def test_parser_instance_reuse(self, sample_docx, sample_docx_with_tables):
        """Test reusing parser instance."""
        parser = DocxParser()

        result1 = parser.parse(sample_docx)
        result2 = parser.parse(sample_docx_with_tables)

        assert result1.source != result2.source
        assert result1.content != result2.content

    def test_parser_with_all_options(self, sample_docx_with_tables, output_dir):
        """Test parser with all options configured."""
        parser = DocxParser(
            extract_images=True,
            image_placeholder="[IMG:{num}]",
            vertical_merge=VerticalMergeMode.REPEAT,
            horizontal_merge=HorizontalMergeMode.EXPAND,
            output_format=OutputFormat.MARKDOWN,
            extract_metadata=True,
            hierarchy_mode=HierarchyMode.STYLE,
            max_heading_level=4,
            table_format=TableFormat.MARKDOWN,
            convert_images=True,
        )

        result = parser.parse(sample_docx_with_tables, output_dir)

        assert result.metadata is not None
        assert result.output_format == OutputFormat.MARKDOWN


# ============================================================================
# Heading Pattern Tests
# ============================================================================


@pytest.mark.integration
class TestHeadingPatterns:
    """Tests for custom heading pattern detection."""

    def test_pattern_heading_mode_with_numbered_patterns(self, tmp_path):
        """Test pattern-based heading detection with numbered patterns."""
        try:
            from docx import Document

            doc = Document()
            doc.add_paragraph("1. First Chapter")
            doc.add_paragraph("Content under first chapter.")
            doc.add_paragraph("2. Second Chapter")
            doc.add_paragraph("Content under second chapter.")
            doc.add_paragraph("1) Sub section")
            doc.add_paragraph("Sub section content.")

            path = tmp_path / "numbered_headings.docx"
            doc.save(str(path))

            # Test with custom patterns
            result = parse_docx(
                path,
                hierarchy_mode=HierarchyMode.PATTERN,
                heading_patterns=[
                    (r"^\d+\. ", 1),  # "1. " -> H1
                    (r"^\d+\) ", 2),  # "1) " -> H2
                ],
            )

            assert result.content
            assert "# " in result.content or "## " in result.content
        except ImportError:
            pytest.skip("python-docx not installed")

    def test_pattern_heading_mode_with_roman_numerals(self, tmp_path):
        """Test pattern-based heading detection with roman numerals."""
        try:
            from docx import Document

            doc = Document()
            doc.add_paragraph("I. Introduction")
            doc.add_paragraph("Introduction content.")
            doc.add_paragraph("II. Methods")
            doc.add_paragraph("Methods content.")

            path = tmp_path / "roman_headings.docx"
            doc.save(str(path))

            result = parse_docx(
                path,
                hierarchy_mode=HierarchyMode.PATTERN,
                heading_patterns=[
                    (r"^[IVXLCDMivxlcdm]+\. ", 1),
                ],
            )

            assert result.content
        except ImportError:
            pytest.skip("python-docx not installed")

    def test_pattern_heading_mode_with_korean(self, tmp_path):
        """Test pattern-based heading detection with Korean patterns."""
        try:
            from docx import Document

            doc = Document()
            doc.add_paragraph("가. 첫 번째 장")
            doc.add_paragraph("첫 번째 장 내용.")
            doc.add_paragraph("나. 두 번째 장")
            doc.add_paragraph("두 번째 장 내용.")

            path = tmp_path / "korean_headings.docx"
            doc.save(str(path))

            result = parse_docx(
                path,
                hierarchy_mode=HierarchyMode.PATTERN,
                heading_patterns=[
                    (r"^[가-힣]\. ", 1),
                ],
            )

            assert result.content
        except ImportError:
            pytest.skip("python-docx not installed")

    def test_pattern_heading_mode_with_circled_numbers(self, tmp_path):
        """Test pattern-based heading detection with circled numbers."""
        try:
            from docx import Document

            doc = Document()
            doc.add_paragraph("① 첫 번째 항목")
            doc.add_paragraph("첫 번째 내용.")
            doc.add_paragraph("② 두 번째 항목")
            doc.add_paragraph("두 번째 내용.")

            path = tmp_path / "circled_headings.docx"
            doc.save(str(path))

            result = parse_docx(
                path,
                hierarchy_mode=HierarchyMode.PATTERN,
                heading_patterns=[
                    (r"^[①-⑳] ", 2),
                ],
            )

            assert result.content
        except ImportError:
            pytest.skip("python-docx not installed")


# ============================================================================
# Font Size Based Heading Tests
# ============================================================================


@pytest.mark.integration
class TestFontSizeHeading:
    """Tests for font-size-based heading detection."""

    def test_font_size_heading_mode(self, tmp_path):
        """Test font-size-based heading detection."""
        try:
            from docx import Document
            from docx.shared import Pt

            doc = Document()

            # Add heading with large font
            para = doc.add_paragraph()
            run = para.add_run("Large Title")
            run.font.size = Pt(24)

            doc.add_paragraph("Normal content.")

            # Add subheading with medium font
            para2 = doc.add_paragraph()
            run2 = para2.add_run("Medium Heading")
            run2.font.size = Pt(18)

            doc.add_paragraph("More content.")

            path = tmp_path / "font_size_headings.docx"
            doc.save(str(path))

            result = parse_docx(
                path,
                hierarchy_mode=HierarchyMode.FONT_SIZE,
            )

            assert result.content
        except ImportError:
            pytest.skip("python-docx not installed")


# ============================================================================
# Vertical Merge Mode Tests
# ============================================================================


@pytest.mark.integration
class TestVerticalMergeModes:
    """Tests for different vertical merge handling modes."""

    def test_vertical_merge_first_only(self, sample_docx_with_tables):
        """Test vertical merge first_only mode."""
        result = parse_docx(
            sample_docx_with_tables,
            vertical_merge=VerticalMergeMode.FIRST_ONLY,
        )

        assert result.content

    def test_vertical_merge_all_modes_with_merged_table(self, tmp_path):
        """Test all vertical merge modes with a table that has merged cells."""
        try:
            from docx import Document
            from docx.oxml.ns import qn
            from docx.oxml import OxmlElement

            doc = Document()
            table = doc.add_table(rows=3, cols=2)
            table.style = "Table Grid"

            # Fill cells
            table.cell(0, 0).text = "Header 1"
            table.cell(0, 1).text = "Header 2"
            table.cell(1, 0).text = "Merged"
            table.cell(1, 1).text = "Data 1"
            table.cell(2, 0).text = ""  # Part of merge
            table.cell(2, 1).text = "Data 2"

            # Manually set vertical merge
            tc1 = table.cell(1, 0)._tc
            tcPr1 = tc1.get_or_add_tcPr()
            vMerge1 = OxmlElement("w:vMerge")
            vMerge1.set(qn("w:val"), "restart")
            tcPr1.append(vMerge1)

            tc2 = table.cell(2, 0)._tc
            tcPr2 = tc2.get_or_add_tcPr()
            vMerge2 = OxmlElement("w:vMerge")
            tcPr2.append(vMerge2)

            path = tmp_path / "merged_table.docx"
            doc.save(str(path))

            # Test REPEAT mode
            result_repeat = parse_docx(path, vertical_merge=VerticalMergeMode.REPEAT)
            assert result_repeat.content

            # Test EMPTY mode
            result_empty = parse_docx(path, vertical_merge=VerticalMergeMode.EMPTY)
            assert result_empty.content

            # Test FIRST_ONLY mode
            result_first = parse_docx(path, vertical_merge=VerticalMergeMode.FIRST_ONLY)
            assert result_first.content

        except ImportError:
            pytest.skip("python-docx not installed")


# ============================================================================
# Horizontal Merge Mode Tests
# ============================================================================


@pytest.mark.integration
class TestHorizontalMergeModes:
    """Tests for different horizontal merge handling modes."""

    def test_horizontal_merge_repeat_mode(self, sample_docx_with_tables):
        """Test horizontal merge repeat mode."""
        result = parse_docx(
            sample_docx_with_tables,
            horizontal_merge=HorizontalMergeMode.REPEAT,
        )

        assert result.content

    def test_horizontal_merge_with_colspan_table(self, tmp_path):
        """Test horizontal merge with table that has colspan."""
        try:
            from docx import Document

            doc = Document()
            table = doc.add_table(rows=2, cols=3)
            table.style = "Table Grid"

            # Merge cells in first row
            table.cell(0, 0).merge(table.cell(0, 2))
            table.cell(0, 0).text = "Merged Header"

            table.cell(1, 0).text = "Col 1"
            table.cell(1, 1).text = "Col 2"
            table.cell(1, 2).text = "Col 3"

            path = tmp_path / "colspan_table.docx"
            doc.save(str(path))

            # Test all modes
            result_expand = parse_docx(path, horizontal_merge=HorizontalMergeMode.EXPAND)
            assert result_expand.content

            result_single = parse_docx(path, horizontal_merge=HorizontalMergeMode.SINGLE)
            assert result_single.content

            result_repeat = parse_docx(path, horizontal_merge=HorizontalMergeMode.REPEAT)
            assert result_repeat.content

        except ImportError:
            pytest.skip("python-docx not installed")


# ============================================================================
# Table Format Tests (Extended)
# ============================================================================


@pytest.mark.integration
class TestTableFormatExtended:
    """Extended tests for table format conversion."""

    def test_all_table_formats_with_complex_table(self, tmp_path):
        """Test all table formats with a complex table."""
        try:
            from docx import Document

            doc = Document()
            table = doc.add_table(rows=4, cols=4)
            table.style = "Table Grid"

            # Fill with varied content
            for i, row in enumerate(table.rows):
                for j, cell in enumerate(row.cells):
                    if i == 0:
                        cell.text = f"Header {j+1}"
                    else:
                        cell.text = f"Data {i},{j}"

            path = tmp_path / "complex_table.docx"
            doc.save(str(path))

            # Test all formats
            for fmt in [TableFormat.MARKDOWN, TableFormat.HTML, TableFormat.JSON, TableFormat.TEXT]:
                result = parse_docx(path, table_format=fmt)
                assert result.content

        except ImportError:
            pytest.skip("python-docx not installed")

    def test_table_with_special_characters(self, tmp_path):
        """Test table parsing with special characters that need escaping."""
        try:
            from docx import Document

            doc = Document()
            table = doc.add_table(rows=2, cols=2)
            table.style = "Table Grid"

            table.cell(0, 0).text = "Header | With | Pipes"
            table.cell(0, 1).text = "Header <with> tags"
            table.cell(1, 0).text = "Data\nwith\nnewlines"
            table.cell(1, 1).text = "Data \"with\" quotes"

            path = tmp_path / "special_chars_table.docx"
            doc.save(str(path))

            result = parse_docx(path, table_format=TableFormat.MARKDOWN)
            assert result.content
            # Pipes should be escaped in markdown
            assert "\\|" in result.content or "|" in result.content

        except ImportError:
            pytest.skip("python-docx not installed")


# ============================================================================
# Result Methods Tests
# ============================================================================


@pytest.mark.integration
class TestResultMethodsExtended:
    """Extended tests for ParseResult methods."""

    def test_result_to_dict(self, sample_docx):
        """Test converting result to dictionary."""
        result = parse_docx(sample_docx, extract_metadata=True)

        # Use to_json() which returns a JSON string, then parse it
        json_str = result.to_json()
        result_dict = json.loads(json_str)
        assert isinstance(result_dict, dict)
        assert "content" in result_dict

    def test_result_to_json_string(self, sample_docx):
        """Test converting result to JSON string."""
        result = parse_docx(sample_docx)

        json_str = result.to_json()
        assert isinstance(json_str, str)
        # Validate JSON
        parsed = json.loads(json_str)
        assert "content" in parsed

    def test_result_replace_placeholders(self, sample_docx_with_images):
        """Test replacing image placeholders with descriptions."""
        result = parse_docx(sample_docx_with_images)

        # Create mock descriptions using index (ImageInfo uses index, not image_id)
        descriptions = {
            img.index: f"Description for image {img.index}"
            for img in result.images_list
        }

        new_content = result.replace_placeholders(descriptions)
        assert isinstance(new_content, str)

        # Check that placeholder replacement worked
        if result.images_list:
            # Verify it's a valid string result
            assert len(new_content) > 0

    def test_result_save_all_formats(self, sample_docx, output_dir):
        """Test saving result in all available formats."""
        result = parse_docx(sample_docx, extract_metadata=True)

        # Save markdown
        md_path = output_dir / "test.md"
        result.save_markdown(md_path)
        assert md_path.exists()

        # Save text
        txt_path = output_dir / "test.txt"
        result.save_text(txt_path)
        assert txt_path.exists()

        # Save JSON
        json_path = output_dir / "test.json"
        result.save_json(json_path)
        assert json_path.exists()
        # Validate JSON content
        with open(json_path) as f:
            data = json.load(f)
            assert "content" in data


# ============================================================================
# Image Extraction Extended Tests
# ============================================================================


@pytest.mark.integration
class TestImageExtractionExtended:
    """Extended tests for image extraction functionality."""

    def test_extract_multiple_images(self, tmp_path):
        """Test extracting multiple images from a document."""
        try:
            from docx import Document
            from docx.shared import Inches
            from PIL import Image
            import io

            # Create multiple test images
            colors = ["red", "green", "blue"]
            img_paths = []
            for i, color in enumerate(colors):
                img = Image.new("RGB", (50, 50), color=color)
                img_path = tmp_path / f"test_image_{i}.png"
                img.save(str(img_path))
                img_paths.append(img_path)

            doc = Document()
            doc.add_heading("Document with Multiple Images", level=1)

            for i, img_path in enumerate(img_paths):
                doc.add_paragraph(f"Image {i+1}:")
                doc.add_picture(str(img_path), width=Inches(1.0))

            docx_path = tmp_path / "multiple_images.docx"
            doc.save(str(docx_path))

            output = tmp_path / "output"
            output.mkdir()

            result = parse_docx(docx_path, output_dir=output, extract_images=True)

            assert result.image_count >= 3
            assert len(result.images_list) >= 3

        except ImportError:
            pytest.skip("python-docx or Pillow not installed")

    def test_image_info_properties(self, sample_docx_with_images, output_dir):
        """Test ImageInfo properties."""
        result = parse_docx(
            sample_docx_with_images,
            output_dir=output_dir,
            extract_images=True,
        )

        if result.images_list:
            img_info = result.images_list[0]
            # ImageInfo has index, name, path, original_name, data attributes
            assert img_info.index >= 1
            assert img_info.name
            assert img_info.data is not None


# ============================================================================
# Config and ParseConfig Tests
# ============================================================================


@pytest.mark.integration
class TestParseConfigIntegration:
    """Integration tests for ParseConfig."""

    def test_parse_with_config_object(self, sample_docx_with_tables, output_dir):
        """Test parsing using a ParseConfig object."""
        from docx_parser.config import (
            ParseConfig,
            ImageConfig,
            TableConfig,
            HierarchyConfig,
            MetadataConfig,
        )

        # ParseConfig uses structured sub-configs
        config = ParseConfig(
            output_format=OutputFormat.MARKDOWN,
            image=ImageConfig(extract=True, convert_to_png=True),
            table=TableConfig(format=TableFormat.MARKDOWN),
            hierarchy=HierarchyConfig(mode=HierarchyMode.STYLE),
            metadata=MetadataConfig(extract=True),
        )

        # Create parser with individual parameters from config
        parser = DocxParser(
            extract_images=config.image.extract,
            extract_metadata=config.metadata.extract,
            hierarchy_mode=config.hierarchy.mode,
            table_format=config.table.format,
            output_format=config.output_format,
        )
        result = parser.parse(sample_docx_with_tables, output_dir)

        assert result.metadata is not None
        assert result.output_format == OutputFormat.MARKDOWN


# ============================================================================
# Pattern Conversion Tests
# ============================================================================


@pytest.mark.integration
class TestPatternConversion:
    """Tests for heading pattern conversion in DocxParser."""

    def test_convert_to_regex_number_dot(self):
        """Test number with dot pattern conversion."""
        parser = DocxParser(
            hierarchy_mode=HierarchyMode.PATTERN,
            heading_patterns=[("1. ", 1)],  # Pattern string, not regex
        )
        # The parser should convert "1. " to a regex
        assert parser.heading_patterns is not None
        assert len(parser.heading_patterns) == 1

    def test_convert_to_regex_number_paren(self):
        """Test number with parenthesis pattern."""
        parser = DocxParser(
            hierarchy_mode=HierarchyMode.PATTERN,
            heading_patterns=[("1) ", 2)],
        )
        assert parser.heading_patterns is not None

    def test_convert_to_regex_uppercase_letter(self):
        """Test uppercase letter pattern."""
        parser = DocxParser(
            hierarchy_mode=HierarchyMode.PATTERN,
            heading_patterns=[("A. ", 1)],
        )
        assert parser.heading_patterns is not None

    def test_convert_to_regex_lowercase_letter(self):
        """Test lowercase letter pattern."""
        parser = DocxParser(
            hierarchy_mode=HierarchyMode.PATTERN,
            heading_patterns=[("a) ", 2)],
        )
        assert parser.heading_patterns is not None

    def test_convert_to_regex_already_regex(self):
        """Test pattern that is already a regex."""
        parser = DocxParser(
            hierarchy_mode=HierarchyMode.PATTERN,
            heading_patterns=[(r"^\d+\. ", 1)],  # Already a regex
        )
        assert parser.heading_patterns is not None

    def test_convert_to_regex_korean_consonant(self):
        """Test Korean consonant pattern."""
        parser = DocxParser(
            hierarchy_mode=HierarchyMode.PATTERN,
            heading_patterns=[("가. ", 1)],
        )
        assert parser.heading_patterns is not None

    def test_convert_to_regex_circled_number(self):
        """Test circled number pattern."""
        parser = DocxParser(
            hierarchy_mode=HierarchyMode.PATTERN,
            heading_patterns=[("① ", 1)],
        )
        assert parser.heading_patterns is not None

    def test_invalid_regex_pattern(self):
        """Test invalid regex pattern raises ValueError."""
        with pytest.raises(ValueError, match="Invalid heading pattern"):
            parser = DocxParser(
                hierarchy_mode=HierarchyMode.PATTERN,
                heading_patterns=[(r"^[invalid", 1)],  # Invalid regex
            )

    def test_fallback_pattern_escaping(self):
        """Test fallback pattern escaping for unknown patterns."""
        parser = DocxParser(
            hierarchy_mode=HierarchyMode.PATTERN,
            heading_patterns=[("*** ", 1)],  # Unknown pattern, should be escaped
        )
        assert parser.heading_patterns is not None


# ============================================================================
# Error Handling Tests
# ============================================================================


@pytest.mark.integration
class TestErrorHandling:
    """Tests for error handling in DocxParser."""

    def test_parse_nonexistent_file(self):
        """Test parsing non-existent file raises FileNotFoundError."""
        parser = DocxParser()
        with pytest.raises(FileNotFoundError):
            parser.parse("/nonexistent/path/to/file.docx")

    def test_parse_invalid_file(self, tmp_path):
        """Test parsing invalid file raises appropriate error."""
        # Create a text file with .docx extension
        invalid_file = tmp_path / "invalid.docx"
        invalid_file.write_text("This is not a valid DOCX file")

        parser = DocxParser()
        with pytest.raises(Exception):  # Could be zipfile.BadZipFile or similar
            parser.parse(invalid_file)

    def test_parse_empty_file(self, tmp_path):
        """Test parsing empty file raises appropriate error."""
        empty_file = tmp_path / "empty.docx"
        empty_file.write_bytes(b"")

        parser = DocxParser()
        with pytest.raises(Exception):
            parser.parse(empty_file)


# ============================================================================
# Output Format Tests
# ============================================================================


@pytest.mark.integration
class TestOutputFormats:
    """Tests for different output formats."""

    def test_text_output_format(self, sample_docx):
        """Test TEXT output format."""
        result = parse_docx(sample_docx, output_format=OutputFormat.TEXT)

        assert result.output_format == OutputFormat.TEXT
        assert result.text_content is not None

    def test_json_output_format(self, sample_docx):
        """Test JSON output format."""
        result = parse_docx(sample_docx, output_format=OutputFormat.JSON)

        assert result.output_format == OutputFormat.JSON
        # Content should be a list of blocks
        assert isinstance(result.content, list)

    def test_markdown_output_format(self, sample_docx):
        """Test MARKDOWN output format."""
        result = parse_docx(sample_docx, output_format=OutputFormat.MARKDOWN)

        assert result.output_format == OutputFormat.MARKDOWN
        assert isinstance(result.content, str)
